
/**
 * DATA TYPE DEFINITIONS
 * =====================
 * This file contains all the interfaces used throughout the application.
 * 
 * Key Concepts:
 * 1. Raw Data (CSV) -> Parsed Data (Row Interfaces) -> Aggregated Stats.
 * 2. 'AnyDataRow' is a discriminated union used for generic components like HistoryTable.
 */

export type PortfolioType = 'PPK' | 'CRYPTO' | 'IKE' | 'OMF' | 'CASH';

/**
 * Represents a single month of PPK data.
 * Derived from CSV/PPK.ts.
 */
export interface PPKDataRow {
  date: string;
  dateObj: Date;
  employeeContribution: number;
  employerContribution: number;
  stateContribution: number;
  fundProfit: number; // "Zysk z funduszu" from CSV - raw fund performance
  profit: number;     // "Całkowity Zysk" - User's Net Profit (Total Value - User Contribution)
  tax: number;        // Potential capital gains tax
  roi: number;        // Return on Investment (Profit / Contribution)
  exitRoi: number;    // ROI if money is withdrawn immediately (penalties applied)
  totalValue: number; // Calculated: Employee + Employer + State + FundProfit
}

/**
 * Represents a single month of Crypto or IKE history.
 * Generic structure for simple Time-Series data.
 */
export interface CryptoDataRow {
  date: string;
  dateObj: Date;
  investment: number; // Net Capital Invested ("Wkład")
  profit: number;     // Net Profit/Loss ("Zysk")
  roi: number;
  totalValue: number; // Calculated: Investment + Profit
}

export interface IKEDataRow extends CryptoDataRow {
  // Value of the portfolio if it were a standard taxable account (Profit - 19% Tax)
  taxedTotalValue?: number;
}

/**
 * Represents a single month of Cash history.
 */
export interface CashDataRow {
  date: string;
  dateObj: Date;
  value: number;
}

/**
 * Represents a specific Asset in the OMF (One More Fund?) portfolio.
 * Unlike PPK/Crypto which are time-series, this is a snapshot of current positions.
 */
export interface OMFDataRow {
  status: string;       // e.g., 'Otwarta' (Open), 'Zamknięta' (Closed), 'Gotówka' (Cash)
  portfolio: string;    // Sub-portfolio: 'PPK', 'IKE', 'Krypto', 'Gotówka'
  type: string;         // Asset Class: 'ETF', 'Akcje' (Stocks), etc.
  symbol: string;       // Ticker: 'AMZN', 'BTC', 'PLN'
  sector: string;       // e.g., 'Technology', 'Consumer Discretionary'
  lastPurchaseDate: string; 
  investmentPeriod: string; // Duration held in days/years
  quantity: number;     
  currentValue: number; // Market Value in PLN
  purchaseValue: number;// Cost Basis in PLN
  profit: number;       // Absolute PnL
  roi: number;          // Percentage Return
  change24h?: number;   // Percentage change in last 24h (Online mode)
  isLivePrice?: boolean; // True if price comes from Online source, False if fallback
}

/**
 * Aggregated Data for the Global Chart.
 * Merges PPK, Crypto, and IKE data into a single timeline.
 */
export interface GlobalHistoryRow {
  date: string;
  investment: number;   // Sum of all invested capital
  profit: number;       // Sum of all profits
  totalValue: number;   // Sum of all market values
  roi: number;          // Global ROI
  cumulativeTwr: number;// Time-Weighted Return (Geometric linking) for Crypto+IKE parts
  ppkShare: number;     // 0.0 - 1.0 ratio of PPK in total portfolio
  cryptoShare: number;  // 0.0 - 1.0 ratio of Crypto in total portfolio
  ikeShare: number;     // 0.0 - 1.0 ratio of IKE in total portfolio
  
  // Specific fields for Heatmap/Analysis excluding PPK (Active Management)
  investmentNoPPK?: number;
  profitNoPPK?: number;
  totalValueNoPPK?: number;

  // Benchmarks (Normalized Percentage Return)
  sp500Return?: number;
  wig20Return?: number;

  // Real Value (Inflation Adjusted)
  realTotalValue?: number;

  // Road to Million Projection
  projectedValue?: number;
}

// Union type for general usage in generic Tables/Charts
export type AnyDataRow = PPKDataRow | CryptoDataRow | IKEDataRow | OMFDataRow | GlobalHistoryRow | CashDataRow;

/**
 * Summary Statistics displayed in top cards.
 */
export interface SummaryStats {
  totalValue: number;
  totalProfit: number;
  currentRoi: number;
  profitTrend?: number; // Month-over-Month profit trend percentage
  dailyTrend?: number;  // 24h Portfolio Value trend percentage
  
  // Performance Metrics (Time-Weighted)
  cagr?: number; // Compound Annual Growth Rate
  ltm?: number;  // Last Twelve Months Return
  ytd?: number;  // Year To Date Return

  // PPK Specific Breakdown
  totalEmployee?: number;
  totalEmployer?: number;
  totalState?: number;
  currentExitRoi?: number;
  
  // Crypto/IKE Specific
  totalInvestment?: number;
  taxSaved?: number; // For IKE: Amount saved due to tax shield (19% of profit)
}

/**
 * Generic Data Validation Report.
 * Generated by parseCSV.
 */
export interface ValidationReport {
  isValid: boolean;
  source?: 'Online' | 'Offline'; // 'Online' = fetched, 'Offline' = local .ts file
  checks: {
    structure: boolean; // Are headers correct?
    dataTypes: boolean; // Can we parse numbers/dates?
    logic: boolean;     // Are values non-negative where expected?
  };
  errors: string[];
  stats: {
    totalRows: number;
    validRows: number;
  };
}

/**
 * Specific Validation for OMF Portfolio.
 * Includes Math Integrity checks (Purchase + Profit ~= Current Value).
 */
export interface OMFValidationReport {
  isConsistent: boolean;
  source?: 'Online' | 'Offline';
  checks: {
    structure: boolean;
    mathIntegrity: boolean; // Crucial check: Purchase + Profit should equal Current Value (within tolerance)
  };
  messages: string[];
  stats: {
    totalAssets: number;
    openAssets: number;
    closedAssets: number;
  };
}
